
name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - update-documentation-instructions
#  pull_request:
#    branches:
#      - dev
  workflow_dispatch:  # allows workflow to be triggered manually

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CUSTOM_DOMAIN: optionaldomain.com
#          CONFIG_FILE: folder/mkdocs.yml
#          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt